# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.2
  subs: 'Microsoft Partner Network(eeb9dfdd-9c17-44c3-a4a0-7529399ce200)'
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Zipping the file
  jobs:
  - job: BuildJob
    # pool:
    #   vmImage: $(vmImageName)
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        # targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'
        
- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    # pool:
    #     vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App ourwebsite'
            inputs:
              azureSubscription: 'Microsoft Partner Network(eeb9dfdd-9c17-44c3-a4a0-7529399ce200)'
              appType: 'webAppLinux'
              appName: 'tzaroon'
              deployToSlotOrASE: true
              resourceGroupName: 'testing'
              slotName: 'production'
              package: '$(Build.ArtifactStagingDirectory)'